### ISSUE TITLE
Advanced topics

### ISSUE THREAD

**Issue by ErikEJ** [GibraltarSoftware/VistaDB.EFCore#3]
Connection pooling - is it enabled by default?

Database creation options - how to specify them with EF Core? https://doc.vistadb.com/#HowTo_IsolatedStorage_Examples.html 

CLR Methods as SQL Functions !

**Comment by kendallmiller** [comment]
I don’t believe it is, and it is recommended when not opening the database in exclusive mode.  You’ll want to enable a pool and open in shared read write for EF.

On Jul 1, 2018, at 10:45 AM, Erik Ejlskov Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:


Connection pooling - is it enabled by default?

Database creation options - how to specify them with EF Core? https://doc.vistadb.com/#HowTo_IsolatedStorage_Examples.html

CLR Methods as SQL Functions !

**Comment by ErikEJ** [comment]
Pooling now in place
