### ISSUE TITLE
Issue with ORDER BY (SELECT 1)

### ISSUE THREAD

**Issue by ErikEJ** [GibraltarSoftware/VistaDB.EFCore#5]
This cannot be interpreted by the VistaDB engine, for workaround, see: https://github.com/aspnet/EntityFrameworkCore/issues/12519

**Comment by kendallmiller** [comment]
We may be able to easily extend the VistaDB engine to support SELECT 1 as syntax in this position; it not being supported is largely a lack of imagination that this was valid and useful. Reading through the EF ticket I'm surprised that ORDER BY <ordinal> is treated as "order by <column in ordinal position>"; that's a SQL trick I didn't know.  I'll look for the official MS TSQL Documentation on this point so we can refer that to the VistaDB team.

**Comment by kendallmiller** [comment]
OK, it looks like effectively (SELECT 1) is meant to largely obviate the order by expression but still allow offset/fetch (cheeky!) and get around their parser order.  We'll see if we can get this put into the VistaDB engine as effectively "don't order by".
