### ISSUE TITLE
Database creation options - how to expose?

### ISSUE THREAD

**Issue by ErikEJ** [GibraltarSoftware/VistaDB.EFCore#6]
Database creation options - how to specify them with EF Core? https://doc.vistadb.com/#HowTo_IsolatedStorage_Examples.html

Extension methods on the DbContext?

Also need documentation of CREATE DATABASE

**Comment by kendallmiller** [comment]
The documentation on [CREATE DATABASE](http://doc.vistadb.com/#HowTo_CreateDatabasesInCode_SQL.html) is clearly insufficient and out of date (still refers to VistaDB 4 extension as the default):

Forwarded to the VistaDB team.
